- name: Copy MongoDB repo files
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: latest

- name: configuring nodejs repos
  ansible.builtin.shell: mongo --host mongodb-dev.iamadevopsengineer.tech </app/schema/{{ component }}.js