- name: configuring nodejs repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: latest

- name: Application user setup
  ansible.builtin.include_tasks:
    file: app_user.yml