- name: Install Python 3.6
  ansible.builtin.yum:
    name:
      - python36
      - python36
      - python3-devel
    state: installed

- name: Application user setup
  ansible.builtin.include_tasks:
    file: app_user.yml

- name: Download python dependencies
  ansible.builtin.shell: cd /app ; pip3.6 install -r requirements.txt

- name: systemd setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml